using System;
using System.Collections.Generic;
using System.Linq;
using IdleXIdle.Core.Builds;
using IdleXIdle.Core.Characters;
using IdleXIdle.Core.Economy;
using IdleXIdle.Core.Expeditions;
using IdleXIdle.Core.Loot;
using IdleXIdle.Core.Sources;
using Xunit;

namespace IdleXIdle.Core.Tests.Builds;

/// <summary>
/// THE SHARED OVERKILL CARRY GENERATES ONE LEVEL — an original hit's spill carries once, and the
/// carried hit, whatever it kills, carries nothing.
/// </summary>
/// <remarks>
/// <para>
/// The carry's gate read "a skill hit, or any hit while an IMPACT swing is in flight". A carried hit
/// is not a skill hit, so a skill's carry was bounded — but the IMPACT flag (BODY's fifth rung) stays
/// up around the swing's whole landing, nested carries included, so a carried kill under an IMPACT
/// satisfied the gate again and carried at full strength into the next creature, and the next, down
/// the wave. The site's own comment said "one level only" (2026-09-07). The gate reads the hit's
/// PROVENANCE now (<see cref="HitSource"/>): a carry is generated by a Primary hit or an IMPACT
/// swing, and a <see cref="HitSource.Carry"/> hit generates nothing — for every consumer of the field
/// at once, because there is one site.
/// </para>
/// <para>
/// The wave: A dies to the blow (its spill carries, at BODY's fourth-rung share, into B, who survives
/// it); the IMPACT swing that follows the cast kills B with spill, which carries whole into C and
/// kills C; D, behind C, must not be touched by anything at that instant. Before the fix D took the
/// chain's third link.
/// </para>
/// </remarks>
public class carry_chain_test
{
    // THE METRONOME, whose FIRST BEAT waives the opener's wait: the blow lands on the first beat and the
    // IMPACT swing follows it on the second, before the plain swings could kill A themselves (a plain
    // swing's kill carries nothing, so it could not pose the chain). Its doubled first hit changes the
    // sizes, which is why they are measured from the sim rather than guessed.
    private static readonly Character Metronome = CharacterRoster.Get("metronome");

    /// <summary>Five BODY pieces of no class: the fourth rung's carry (0.35) and the fifth's IMPACT swing (+75%, carries whole).</summary>
    private static Hunter FullBody()
    {
        var hunter = new Hunter();
        var types = new[] { ItemBaseType.Helm, ItemBaseType.Chest, ItemBaseType.Gloves, ItemBaseType.Boots, ItemBaseType.Ring };
        foreach (var (t, i) in types.Select((t, i) => (t, i)))
            hunter.Equip(new ItemInstance { InstanceId = $"body{i}", BaseType = t, Rarity = Rarity.Common, SellValue = 1, Element = Source.Body, ItemLevel = 1 });
        return hunter;
    }

    private static Build Blow() => Reachable.Compose(Metronome, new[] { new Reachable.Slot("hammer_blow", "FLATTEN") }, slotCapacity: 3);

    private sealed record Run(List<BattleEvent> Events, WaveMetrics Metrics);

    private static Run Fight(List<WaveCreature> wave, int ceilingMs)
    {
        var champ = new Champion { MaxHealth = 200_000, Health = 200_000 };
        var metrics = new WaveMetrics();
        var (_, events) = SoloBattle.ResolveWave(champ, Blow(), FullBody(), wave, enemyIntervalMs: 900,
                                                 ExpeditionTuning.Default with { TickCeilingMs = ceilingMs }, new Random(3), metrics: metrics);
        return new Run(events, metrics);
    }

    private static WaveCreature C(float health) => new() { MaxHealth = health, Health = health, Damage = 0f, Defense = 0f };

    [Fact]
    public void test_carry_an_impact_swings_carried_kill_does_not_carry_again()
    {
        // ARRANGE — the sizes come from the sim, not a guess: the blow and the IMPACT swing measured
        // on a creature nothing can kill, so the wave below poses exactly the chain.
        var probe = Fight(new List<WaveCreature> { C(1e9f) }, 6_000);
        var strikes = probe.Events.Where(e => e.Kind == BattleEventKind.Strike).ToList();
        var blow = strikes.First(e => e.FromSkill).Amount;
        var impact = strikes.First(e => !e.FromSkill && e.AtMs > strikes.First(s => s.FromSkill).AtMs).Amount;
        Assert.True(impact > 20, $"the IMPACT swing measured {impact} — the fixture is not posing BODY's fifth rung");

        var carryIntoB = (blow - 1f) * 0.35f;                 // A dies to the blow; B takes the fourth rung's share
        var wave = new List<WaveCreature>
        {
            C(1f),                                         // A: dies to the blow, with spill
            C(carryIntoB + impact * 0.5f),                 // B: survives the carry, dies to the IMPACT swing with spill
            C(impact * 0.25f),                             // C: dies to the swing's carried spill — the ONE generated level
            C(1e9f),                                       // D: must never take a second generated carry
        };

        // ACT
        var run = Fight(wave, 6_000);

        // ASSERT — the preconditions first, so a mis-sized fixture fails loudly instead of vacuously.
        var swing = run.Events.First(e => e.Kind == BattleEventKind.Strike && e.Slot == 1 && !e.FromSkill);
        var atSwing = run.Events.Where(e => e.Kind == BattleEventKind.Strike && e.AtMs == swing.AtMs).ToList();
        Assert.Contains(run.Events, e => e.Kind == BattleEventKind.EnemyDown && e.Slot == 1 && e.AtMs == swing.AtMs);   // B died to the swing
        Assert.Contains(atSwing, e => e.Slot == 2);                                                                     // C took the carry
        Assert.Contains(run.Events, e => e.Kind == BattleEventKind.EnemyDown && e.Slot == 2 && e.AtMs == swing.AtMs);   // and died with spill

        // The law: at the swing's instant, B (the swing) and C (its one carry) — and nothing on D.
        Assert.DoesNotContain(atSwing, e => e.Slot == 3);
        Assert.Equal(2, atSwing.Count);
        Assert.True(wave[3].Health >= wave[3].MaxHealth - impact * 3f, "D took more than a swing's worth — a chain reached it");

        // Exactly one carry per original kill: the blow's (into B) and the swing's (into C).
        Assert.Equal(2, run.Metrics.CarriesLanded);
        Assert.Equal(1, run.Metrics.CarryKills);   // C — the carried kill that must reopen nothing
    }

    [Fact]
    public void test_carry_still_carries_once_from_an_original_hit()
    {
        // Not disabled: the blow's spill reaches the next creature, and a skill kill's carry lands once.
        var run = Fight(new List<WaveCreature> { C(1f), C(1e9f) }, 6_000);
        Assert.True(run.Metrics.CarriesLanded >= 1, "the carry no longer carries");
        var blowAt = run.Events.First(e => e.Kind == BattleEventKind.Strike && e.FromSkill).AtMs;
        var atBlow = run.Events.Where(e => e.Kind == BattleEventKind.Strike && e.AtMs == blowAt).ToList();
        Assert.Equal(2, atBlow.Count);   // A, and the carry into B
        Assert.Contains(atBlow, e => e.Slot == 1);
    }
}
