using System.Collections.Generic;
using ResonanceHunter.Core.Animation;

namespace ResonanceHunter.Client;

/// <summary>
/// One rig part: the texture drawn for a bone, plus where that texture pivots.
/// </summary>
/// <param name="Id">Bone id (matches the Core <see cref="Bone"/>).</param>
/// <param name="Parent">Parent bone id, or null for the root.</param>
/// <param name="TextureKey">AssetLibrary key (the part PNG's basename).</param>
/// <param name="Offset">Attach point in the PARENT's local space at rest — i.e. the parent's child-joint
/// pixel minus the parent's pivot pixel. For the root this is zero (its pivot sits at the root position).</param>
/// <param name="Pivot">The proximal joint in THIS part's own pixels — handed to SpriteBatch as the draw
/// origin, and the point the part rotates about.</param>
/// <param name="DrawOrder">Back-to-front paint order (independent of the parent→child transform order).</param>
/// <param name="RestAngle">
/// Constant rotation applied before any clip, in radians.
/// </param>
/// <remarks>
/// The source figure is drawn in an A-POSE — arms held out — because that is what lets a rectangle
/// decomposition separate an arm from the torso at all. Nobody stands like that, so the arms are
/// rotated back down here. Clip angles add on top, which is the normal rig arrangement: the art's
/// pose is a cutting convenience, the rest angles are the character's actual stance.
/// </remarks>
public sealed record HunterPart(
    string Id,
    string? Parent,
    string TextureKey,
    Vec2 Offset,
    Vec2 Pivot,
    int DrawOrder,
    float RestAngle = 0f);

/// <summary>
/// The player Hunter as a homebrew cutout rig (batch-1 art, ADR-002 / Option B).
///
/// <para>Hand-authored here (v1) rather than loaded from the delivered <c>hunter_rig.json</c>, whose
/// coordinates were unusable. All rest angles are 0: each part PNG is drawn in its natural rest
/// orientation, so the renderer draws it unrotated at rest and only rotates it for poses. Coordinates are
/// in authored part pixels; the whole assembled figure is fit-scaled to the champion box at draw time.</para>
///
/// <para>These numbers are the tuning surface — verified by eye against the assembled preview
/// (RH_SHOT_MODE=rig). Once locked they can be externalised back to a corrected JSON.</para>
/// </summary>
public static class HunterRig
{
    public static readonly IReadOnlyList<HunterPart> Parts = new[]
    {
        // GENERATED by tools/asset-pipeline/cut_rig_parts.py — do not hand-tune.
        // Body parts are cut from hunter_rig_base — a figure authored FOR the cutter (A-pose,
        // empty hands, nothing draped) — on disjoint, measured, tiling boxes. The two
        // shoulder bones instead use DRAWN pauldrons: a joint cover taken from the body
        // carries the resting pose's lighting and shows as a patch once the arm moves.
        new HunterPart("arm_upper_off", "torso", "hunter_part_arm_upper_off", new Vec2(55, -82), new Vec2(4, 8), 1, 0.63f),
        new HunterPart("arm_fore_off", "arm_upper_off", "hunter_part_arm_fore_off", new Vec2(46, 46), new Vec2(50, 0), 2),
        new HunterPart("hand_off", "arm_fore_off", "hunter_part_hand_off", new Vec2(12, 36), new Vec2(29, 0), 3),
        new HunterPart("leg_thigh_off", "pelvis", "hunter_part_leg_thigh_off", new Vec2(37, 42), new Vec2(36, 0), 4),
        new HunterPart("leg_shin_off", "leg_thigh_off", "hunter_part_leg_shin_off", new Vec2(28, 100), new Vec2(64, 0), 5),
        new HunterPart("foot_off", "leg_shin_off", "hunter_part_foot_off", new Vec2(14, 60), new Vec2(78, 0), 6),
        new HunterPart("pelvis", null, "hunter_part_pelvis", new Vec2(0, 0), new Vec2(86, 0), 7),
        new HunterPart("torso", "pelvis", "hunter_part_torso", new Vec2(0, 0), new Vec2(52, 90), 8),
        new HunterPart("leg_thigh_main", "pelvis", "hunter_part_leg_thigh_main", new Vec2(-43, 42), new Vec2(73, 0), 9),
        new HunterPart("leg_shin_main", "leg_thigh_main", "hunter_part_leg_shin_main", new Vec2(-19, 100), new Vec2(54, 0), 10),
        new HunterPart("foot_main", "leg_shin_main", "hunter_part_foot_main", new Vec2(-12, 60), new Vec2(52, 0), 11),
        new HunterPart("head", "torso", "hunter_part_head", new Vec2(0, -90), new Vec2(106, 168), 12),
        new HunterPart("arm_upper_main", "torso", "hunter_part_arm_upper_main", new Vec2(-56, -82), new Vec2(72, 8), 13, -0.63f),
        new HunterPart("arm_fore_main", "arm_upper_main", "hunter_part_arm_fore_main", new Vec2(-46, 46), new Vec2(38, 0), 14),
        new HunterPart("hand_main", "arm_fore_main", "hunter_part_hand_main", new Vec2(-13, 36), new Vec2(25, 0), 15),
        new HunterPart("shoulder_main", "torso", "hunter_part_shoulder_main", new Vec2(-56, -82), new Vec2(29, 22), 16),
        new HunterPart("shoulder_off", "torso", "hunter_part_shoulder_off", new Vec2(55, -82), new Vec2(29, 22), 17),
    };

    /// <summary>Build the Core geometry rig (no textures) from the part table.</summary>
    public static Rig BuildRig()
    {
        var bones = new List<Bone>();
        foreach (var p in Parts)
            bones.Add(new Bone { Id = p.Id, ParentId = p.Parent, Offset = p.Offset });
        return new Rig(bones);
    }
}
