#!/usr/bin/env python3
"""THE SKILL TABLES IN THE DESIGN DOC ARE THE CATALOGUE, OR THEY ARE A LIE.

`design/gdd/skill-slots-and-skill-trees.md` section 6 lists all twelve skills, their twenty-four
variations, the Source each belongs to and the seventy-two reinforcements. It is the document a designer
reads to answer "what does this branch do", and every one of those rows also exists in
`src/IdleXIdle.Core/Builds/SkillCatalogue.cs`, where it is the thing the fight actually runs.

Two copies of one design, and the copy that goes stale is always the prose. It had: SHEAR, SPUR, SEAL,
GROUPING and eighteen other reinforcements the rework replaced, THIRST for what is now SIPHON, and no
Source column at all — so the six variations that moved Source could not have been wrong in it, because
it never said.

So the doc's tables are GENERATED from the catalogue, and this checks they still match. Run with
`--write` to regenerate them.

    python tools/check_skill_doc.py            # verify (used by check_all.sh)
    python tools/check_skill_doc.py --write    # regenerate after a catalogue change
"""
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOGUE = os.path.join(ROOT, "src", "IdleXIdle.Core", "Builds", "SkillCatalogue.cs")
DOC = os.path.join(ROOT, "design", "gdd", "skill-slots-and-skill-trees.md")

START = "<!-- SKILLS: generated by tools/check_skill_doc.py — edit SkillCatalogue.cs, not this -->"
END = "<!-- /SKILLS -->"


def strip_comments(text):
    """Line comments only — the catalogue has no block comments, and a `//` inside a string
    would be a URL, of which it has none."""
    out = []
    for line in text.split("\n"):
        stripped = line.lstrip()
        out.append("" if stripped.startswith("//") else line)
    return "\n".join(out)


def read_catalogue():
    src = strip_comments(io.open(CATALOGUE, encoding="utf-8").read())
    body = src[src.index("public static IReadOnlyList<SkillDef> All"):]

    # One entry per skill: id, name, style, kind, then its own line.
    heads = list(re.finditer(
        r'new\("(?P<id>[a-z_]+)",\s*"(?P<name>[A-Z ]+)",\s*Style\.(?P<style>\w+),\s*'
        r'SkillKind\.(?P<kind>\w+),\s*SkillEffect\.\w+,\s*\n\s*"(?P<line>[^"]*)"', body))
    if not heads:
        sys.exit("check_skill_doc: no skills found — the catalogue's shape changed")

    skills = []
    for i, h in enumerate(heads):
        chunk = body[h.end():heads[i + 1].start() if i + 1 < len(heads) else len(body)]
        variations = []
        for v in re.finditer(
                r'V\("(?P<name>[A-Z ]+)",\s*"(?P<line>[^"]*)",\s*\n\s*Source\.(?P<source>\w+),', chunk):
            tail = chunk[v.end():]
            nxt = re.search(r'\n\s*V\("', tail)
            tail = tail[:nxt.start()] if nxt else tail
            reinforcements = [(m.group(1), m.group(2)) for m in
                              re.finditer(r'\("(?P<n>[A-Z ]+)",\s*"(?P<l>[^"]*)",', tail)]
            variations.append((v.group("name"), v.group("source"), v.group("line"), reinforcements))
        skills.append((h.group("id"), h.group("name"), h.group("style"),
                       h.group("kind"), h.group("line"), variations))
    return skills


def render(skills):
    by_style = {}
    for s in skills:
        by_style.setdefault(s[2], []).append(s)

    out = [START, ""]
    for style, group in by_style.items():
        out.append(f"### {style.upper()}")
        out.append("")
        out.append("| | Entry | Source | Effect |")
        out.append("|---|---|---|---|")
        for _id, name, _style, kind, line, variations in group:
            slot = "**Active**" if kind == "Active" else "**Passive**"
            out.append(f"| {slot} | **{name}** | — | {line} |")
            for vname, vsource, vline, reinforcements in variations:
                out.append(f"| ▸ | **{vname}** | {vsource.upper()} | {vline} |")
                for rname, rline in reinforcements:
                    out.append(f"| | {rname} | | {rline} |")
        out.append("")
    out.append(END)
    return "\n".join(out)


def main():
    skills = read_catalogue()
    if len(skills) != 12:
        sys.exit(f"check_skill_doc: read {len(skills)} skills, expected 12")
    variations = sum(len(s[5]) for s in skills)
    reinforcements = sum(len(r) for s in skills for _, _, _, r in s[5])
    if variations != 24 or reinforcements != 72:
        sys.exit(f"check_skill_doc: read {variations} variations and {reinforcements} "
                 "reinforcements, expected 24 and 72")

    wanted = render(skills)
    doc = io.open(DOC, encoding="utf-8").read()
    if START not in doc or END not in doc:
        sys.exit(f"check_skill_doc: {os.path.relpath(DOC, ROOT)} has no generated block "
                 f"— add the {START} / {END} markers")

    head, rest = doc.split(START, 1)
    _, tail = rest.split(END, 1)
    have = START + rest.split(END, 1)[0] + END

    if "--write" in sys.argv:
        io.open(DOC, "w", encoding="utf-8", newline="").write(head + wanted + tail)
        print(f"   wrote {len(skills)} skills, {variations} variations, "
              f"{reinforcements} reinforcements into the design doc.")
        return

    if have.strip() != wanted.strip():
        sys.exit("check_skill_doc: the design doc's skill tables no longer match the catalogue.\n"
                 "   run: python tools/check_skill_doc.py --write")
    print(f"   the design doc's {len(skills)} skills, {variations} variations and "
          f"{reinforcements} reinforcements are the catalogue's.")


if __name__ == "__main__":
    main()
